# Generated by Django 4.2.3 on 2023-07-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
