# Generated by Django 4.2.3 on 2023-07-29 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_message_reciever_alter_userinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='point',
            new_name='points',
        ),
        migrations.AddField(
            model_name='message',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_user', to='posts.userinfo'),
        ),
    ]
