# Generated by Django 4.2.3 on 2023-07-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_message_receiver_alter_message_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
